= Kubernetes Maven Sample

This example will show how to deploy a Java application to a Kubernetes cluster using Maven. It requires to run a Couchbase server. It can be easily started on https://github.com/couchbase-guides/couchbase-amazon-cli[AWS] or using https://github.com/couchbase-guides/couchbase-docker[Docker].

== Main Targets

. `mvn package`: Builds the WAR file
. `mvn install`: Builds the Docker image
. `mvn exec:java`: Runs the application with a Couchbase server running on `localhost`
. `mvn fabric8:apply`: Deploys the application to Kubernetes
.. By default, the Kubernetes cluster is `localhost`. Set KUBERNETES_MASTER environment variable to point to Kubernetes master.

== Additional Targets

. `mvn fabric8:build`: Builds the Docker image and generated Kubernetes resources
. `mvn fabric8:resource`: Generates the Kubernetes configuration file in `target/classes/META-INF/fabric8` directory

More content on deploying your Java applications with Kubernetes at https://github.com/arun-gupta/kubernetes-java-sample/.

